import { AppHeader } from "@/components/app-header"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils"
import { ClerkProvider } from "@clerk/nextjs"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Metadata } from "next"
import { Geist_Mono, Roboto, Sora, Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({subsets:['latin'],variable:'--font-sans'})

const sora = Sora({ subsets: ["latin"], variable: "--font-display" })

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "antialiased",
        fontMono.variable,
        "font-sans",
        inter.variable,
        sora.variable
      )}
    >
      <body>
        <SpeedInsights />
        <ClerkProvider
          signInFallbackRedirectUrl="/"
          signInForceRedirectUrl="/"
          signUpFallbackRedirectUrl="/account/setup"
          signUpForceRedirectUrl="/account/setup"
        >
          <ThemeProvider>
            <AppHeader />
            {children}
            <Toaster richColors />
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
